let data = [
    {songName: `Hold on Love`,
    path: 'Hold_on-LoveMusic',
    poster:'HoldOnLove',
    singer:'Dan Balan',
    timeSong: '3:39'},

    {songName: `Ghostbusters`,
    path: 'GhostbustersMusic',
    poster:'ghostbusters',
    singer:'Ray Parker Jr',
    timeSong: '4:12'},

    {songName: `Californication`,
    path: 'CalifornicationMusic',
    poster:'californication',
    singer:'Red Hot Chili Peppers',
    timeSong: '5:29'},

    {songName: `I Cant Stop`,
    path: 'I_Cant_Stop(Original Club Mix)Music',
    poster:'ICantStop',
    singer:'Andrew T & Flashtronica',
    timeSong: '3:48'},

    {songName: `Maybe`,
    path: 'MaybeMusic',
    poster:'maybe',
    singer:'Brainstorm',
    timeSong: '4:12'},

    {songName: `Supergirl`,
    path: 'SupergirlMusic',
    poster:'Supergirl',
    singer:'Anna Naklab',
    timeSong: '3:32'},

    {songName: `Supergirls dont cry`,
    path: 'supergirls_dont_cryMusic',
    poster:'SupergirlsDontCry',
    singer:'Reamonn',
    timeSong: '4:06'},

    {songName: `Pretty young girl`,
    path: '- Pretty young girl',
    poster:'PrettyYoungGirl',
    singer:'Bad Boys Blue',
    timeSong: '3:33'},

    {songName: `Lead The Way`,
    path: '- Lead The Way (Record Mix) radiorecord.fm',
    poster:'LeadTheWay',
    singer:'Tonic feat Erick Gold',
    timeSong: '5:33'},

    {songName: `The Unforgiven`,
    path: '- The Unforgiven',
    poster:'TheUnforgiven1',
    singer:'Metallica',
    timeSong: '6:37'},

    {songName: `Nothing else matter`,
    path: '- Nothing else matter',
    poster:'NothingElseMatter',
    singer:'Metallica',
    timeSong: '6:30'},

    {songName: `Youre a woman`,
    path: '- Youre a woman, Im your man',
    poster:'YoureAwomanImYourMan',
    singer:'Bad Boys Blue',
    timeSong: '3:58'},

    {songName: `World`,
    path: 'chris_parker_-_world',
    poster:'World',
    singer:'Chris Parker',
    timeSong: '3:36'},

    {songName: `I just died in your arms`,
    path: 'fm-charts_-_komodo_-_i_just_died_in_your_arms_club_radio_edit_(z2.fm)',
    poster:'IJustDiedInYourArms',
    singer:'Komodo',
    timeSong: '3:08'},

    {songName: `Calling`,
    path: 'gari_halliwell_-_calling_(z2.fm)',
    poster:'Colling',
    singer:'Geri Halliwell',
    timeSong: '4:23'},

    {songName: `Written in the stars`,
    path: 'tinie_tempah_feat._eric_turner_-_written_in_the_stars_radio_edit',
    poster:'written_in_the_stars_radio_edit',
    singer:'Tinie Tempah feat. Eric Turner',
    timeSong: '3:28'},

    {songName: `Flashbacks`,
    path: 'inna_-_flashbacks_(z2.fm)',
    poster:'Flashbacks',
    singer:'INNA',
    timeSong: '2:57'},

    {songName: `Glassheart`,
    path: 'leona_lewis_-_glassheart_(z2.fm)',
    poster:'Glassheart',
    singer:'Leona Lewis',
    timeSong: '3:56'},

    {songName: `The color of the night`,
    path: 'lauren_christie_-_the_color_of_the_night',
    poster:'TheColorOfTheNight',
    singer:'Lauren Christy',
    timeSong: '3:57'},

    {songName: `Eshchyo hochu`,
    path: 'zivert_-_eshchyo_hochu',
    poster:'EshchyoHochu',
    singer:'Zivert',
    timeSong: '3:25'},

    {songName: `Lithium`,
    path: 'Lithium',
    poster:'Liyhium',
    singer:'Evanescence',
    timeSong: '3:44'},

];

export default data